# Generated by Django 4.1.4 on 2022-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="json_path",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
