# Generated by Django 4.1.4 on 2022-12-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="related_scan",
            field=models.ManyToManyField(null=True, to="base_models.scan"),
        ),
    ]
