# Generated by Django 4.1.4 on 2022-12-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0002_scan_related_scan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scan",
            old_name="related_scan",
            new_name="related_scans",
        ),
    ]
