# Generated by Django 4.1.4 on 2022-12-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0003_rename_related_scan_scan_related_scans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="related_scans",
            field=models.ManyToManyField(to="base_models.scan"),
        ),
    ]
