# Generated by Django 4.1.4 on 2022-12-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0007_alter_nifti_parent_tensorderivative"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="is_raw",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="json_path",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="nifti_path",
        ),
        migrations.AddField(
            model_name="scan",
            name="nifti",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base_models.nifti",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="tensor_derivatives",
            field=models.ManyToManyField(to="base_models.tensorderivative"),
        ),
    ]
