# Generated by Django 4.1.4 on 2022-12-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0008_remove_scan_is_raw_remove_scan_json_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="nifti",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base_models.nifti",
            ),
        ),
    ]
