# Generated by Django 4.1.4 on 2022-12-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0010_delete_scan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nifti",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nifti_derivatives_set",
                to="base_models.nifti",
            ),
        ),
        migrations.AlterField(
            model_name="tensorderivative",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tensor_derivatives_set",
                to="base_models.nifti",
            ),
        ),
    ]
