# Generated by Django 4.1.4 on 2022-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0012_session_nifti_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="time",
            field=models.DateTimeField(null=True),
        ),
    ]
