# Generated by Django 4.1.4 on 2022-12-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0013_alter_session_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"get_latest_by": "modified"},
        ),
        migrations.RenameField(
            model_name="session",
            old_name="time",
            new_name="_time",
        ),
    ]
