# Generated by Django 4.1.4 on 2022-12-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0014_alter_session_options_rename_time_session__time"),
    ]

    operations = [
        migrations.AddField(
            model_name="tensorderivative",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derivatives_set",
                to="base_models.session",
            ),
        ),
    ]
