# Generated by Django 4.1.4 on 2022-12-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0015_tensorderivative_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tensorderivative",
            name="session",
        ),
    ]
