# Generated by Django 4.1.4 on 2022-12-25 16:50

import datetime
import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0016_remove_tensorderivative_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=64, null=True)),
                ("first_name", models.CharField(blank=True, max_length=64, null=True)),
                ("last_name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.date(2022, 12, 25)
                            )
                        ],
                        verbose_name="Date of Birth",
                    ),
                ),
                ("custom_attributes", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
