# Generated by Django 4.1.4 on 2022-12-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0018_rename_id_number_subject_pylabber_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ("-pylabber_id",)},
        ),
        migrations.AddField(
            model_name="session",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_set",
                to="base_models.subject",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="pylabber_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
