# Generated by Django 4.1.4 on 2023-01-04 10:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0019_alter_subject_options_session_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="id",
        ),
        migrations.AlterField(
            model_name="subject",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 1, 4))
                ],
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="pylabber_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
