# Generated by Django 4.1.4 on 2023-01-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0020_remove_subject_id_alter_subject_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="id_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
