# Generated by Django 4.1.4 on 2023-01-04 14:49

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0023_remove_study_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "subjects",
                    models.ManyToManyField(blank=True, to="base_models.subject"),
                ),
            ],
            options={
                "verbose_name_plural": "groups",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "subjects",
                    models.ManyToManyField(blank=True, to="base_models.subject"),
                ),
            ],
            options={
                "verbose_name_plural": "conditions",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="study",
            name="conditions",
            field=models.ManyToManyField(blank=True, to="base_models.condition"),
        ),
        migrations.AddField(
            model_name="study",
            name="groups",
            field=models.ManyToManyField(blank=True, to="base_models.group"),
        ),
    ]
