# Generated by Django 4.1.4 on 2023-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0025_alter_subject_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="tensorderivative",
            name="acquisition",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tensorderivative",
            name="atlas",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tensorderivative",
            name="label",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
