# Generated by Django 4.1.4 on 2023-01-06 09:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0027_remove_session__time_session_bids_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 1, 6))
                ],
                verbose_name="Date of Birth",
            ),
        ),
    ]
