# Generated by Django 4.1.4 on 2023-01-08 19:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0028_session_time_alter_subject_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 1, 8))
                ],
                verbose_name="Date of Birth",
            ),
        ),
    ]
