# Generated by Django 4.1.4 on 2023-01-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0030_tensorderivative_software_used"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tensorderivative",
            old_name="parent",
            new_name="nifti_parent",
        ),
        migrations.AddField(
            model_name="tensorderivative",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tensor_derivatives_set",
                to="base_models.session",
                unique=True,
            ),
        ),
    ]
