# Generated by Django 4.1.4 on 2023-01-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0031_rename_parent_tensorderivative_nifti_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tensorderivative",
            name="session",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tensor_derivative",
                to="base_models.session",
            ),
        ),
    ]
