# Generated by Django 4.1.4 on 2023-01-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0033_remove_tensorderivative_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tensorderivative",
            name="session",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tensorderivative",
            name="subject",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
