# Generated by Django 4.1.4 on 2023-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0034_tensorderivative_session_tensorderivative_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="sessions",
            field=models.ManyToManyField(blank=True, to="base_models.session"),
        ),
        migrations.AddField(
            model_name="group",
            name="sessions",
            field=models.ManyToManyField(blank=True, to="base_models.session"),
        ),
    ]
