# Generated by Django 4.1.5 on 2023-01-20 16:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_models", "0035_condition_sessions_group_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="title",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 1, 20))
                ],
                verbose_name="Date of Birth",
            ),
        ),
    ]
